import React from 'react';
import './VehicleRegistration.css'; // Add custom CSS styling if needed

const VehicleRegistration = () => {
  return (
    <div className="vehicle-registration-container">
      <h1 className="heading">Vehicle Registration</h1>
      <p className="paragraph">
        Guidelines for Vehicle Registration at RTO:
      </p>

      <ol className="instructions">
        <li>
          <h3>Step 1: Prepare Required Documents</h3>
          <p>
            Collect all the necessary documents needed for vehicle registration:
          </p>
          <ul>
            <li>Application form (Form 20) duly filled.</li>
            <li>Sale Certificate from the dealer (Form 21).</li>
            <li>Roadworthiness Certificate (Form 22) from the vehicle manufacturer.</li>
            <li>Valid insurance policy.</li>
            <li>Pollution Under Control (PUC) Certificate.</li>
            <li>Proof of address and identity (Aadhaar, Passport, etc.).</li>
            <li>Invoice of the vehicle purchase.</li>
          </ul>
        </li>

        <li>
          <h3>Step 2: Visit the RTO and Submit Application</h3>
          <p>Follow these steps at the RTO office:</p>
          <ol type="a">
            <li>Submit all the required documents at the registration counter.</li>
            <li>Pay the applicable registration fees and road tax.</li>
            <li>Receive the application acknowledgment receipt.</li>
            <li>The RTO will verify the submitted documents and inspect the vehicle if needed.</li>
          </ol>
        </li>

        <li>
          <h3>Step 3: Receive Registration Certificate (RC)</h3>
          <p>Once your application is processed:</p>
          <ul>
            <li>The registration certificate (RC) will be generated by the RTO.</li>
            <li>You can collect the physical RC or download the digital RC from the Sarathi/Parivahan portal.</li>
            <li>Ensure all the details on the RC are correct.</li>
            <li>Keep the RC and insurance policy with you while driving.</li>
          </ul>
        </li>
      </ol>

      <button type="submit" className="btn btn-gradient btn-glow">
        APPLY FOR REGISTRATION
      </button>
    </div>
  );
};

export default VehicleRegistration;
